import {
  FiHome, FiBox, FiShoppingCart, FiUser, FiUsers, FiStar, FiHeart,
  FiCamera, FiPhone, FiMail, FiSettings, FiSearch, FiBell, FiBook,
  FiCalendar, FiCheck, FiClock, FiCloud, FiCode, FiCoffee,
  FiCompass, FiCreditCard, FiDatabase, FiDownload, FiEdit,
  FiEye, FiFile, FiFilm, FiFilter, FiFlag,
  FiFolder, FiGift, FiGlobe, FiGrid, FiHeadphones,
  FiImage, FiInbox, FiKey, FiLayers, FiLayout,
  FiLink, FiLock, FiMap, FiMapPin, FiMenu,
  FiMessageCircle, FiMic, FiMonitor, FiMoon, FiMusic,
  FiNavigation, FiPackage, FiPaperclip, FiPieChart, FiPlay,
  FiPlus, FiPocket, FiPower, FiPrinter, FiRefreshCw,
  FiRepeat, FiSave, FiScissors, FiSend, FiServer,
  FiShare, FiShield, FiShoppingBag, FiSidebar, FiSmile,
  FiSpeaker, FiSquare, FiSun, FiTablet, FiTag,
  FiTarget, FiTerminal, FiThumbsUp, FiTool, FiTrash,
  FiTrendingUp, FiTruck, FiTv, FiUpload, FiVideo,
  FiWifi, FiWind, FiZap, FiZoomIn, FiZoomOut
} from "react-icons/fi";

export const ICON_LIST = [
  { name: "FiHome", icon: FiHome },
  { name: "FiBox", icon: FiBox },
  { name: "FiShoppingCart", icon: FiShoppingCart },
  { name: "FiUser", icon: FiUser },
  { name: "FiUsers", icon: FiUsers },
  { name: "FiStar", icon: FiStar },
  { name: "FiHeart", icon: FiHeart },
  { name: "FiCamera", icon: FiCamera },
  { name: "FiPhone", icon: FiPhone },
  { name: "FiMail", icon: FiMail },
  { name: "FiSettings", icon: FiSettings },
  { name: "FiSearch", icon: FiSearch },
  { name: "FiBell", icon: FiBell },
  { name: "FiBook", icon: FiBook },
  { name: "FiCalendar", icon: FiCalendar },
  { name: "FiCheck", icon: FiCheck },
  { name: "FiClock", icon: FiClock },
  { name: "FiCloud", icon: FiCloud },
  { name: "FiCode", icon: FiCode },
  { name: "FiCoffee", icon: FiCoffee },
  { name: "FiCompass", icon: FiCompass },
  { name: "FiCreditCard", icon: FiCreditCard },
  { name: "FiDatabase", icon: FiDatabase },
  { name: "FiDownload", icon: FiDownload },
  { name: "FiEdit", icon: FiEdit },
  { name: "FiEye", icon: FiEye },
  { name: "FiFile", icon: FiFile },
  { name: "FiFilm", icon: FiFilm },
  { name: "FiFilter", icon: FiFilter },
  { name: "FiFlag", icon: FiFlag },
  { name: "FiFolder", icon: FiFolder },
  { name: "FiGift", icon: FiGift },
  { name: "FiGlobe", icon: FiGlobe },
  { name: "FiGrid", icon: FiGrid },
  { name: "FiHeadphones", icon: FiHeadphones },
  { name: "FiImage", icon: FiImage },
  { name: "FiInbox", icon: FiInbox },
  { name: "FiKey", icon: FiKey },
  { name: "FiLayers", icon: FiLayers },
  { name: "FiLayout", icon: FiLayout },
  { name: "FiLink", icon: FiLink },
  { name: "FiLock", icon: FiLock },
  { name: "FiMap", icon: FiMap },
  { name: "FiMapPin", icon: FiMapPin },
  { name: "FiMenu", icon: FiMenu },
  { name: "FiMessageCircle", icon: FiMessageCircle },
  { name: "FiMic", icon: FiMic },
  { name: "FiMonitor", icon: FiMonitor },
  { name: "FiMoon", icon: FiMoon },
  { name: "FiMusic", icon: FiMusic },
  { name: "FiNavigation", icon: FiNavigation },
  { name: "FiPackage", icon: FiPackage },
  { name: "FiPaperclip", icon: FiPaperclip },
  { name: "FiPieChart", icon: FiPieChart },
  { name: "FiPlay", icon: FiPlay },
  { name: "FiPlus", icon: FiPlus },
  { name: "FiPocket", icon: FiPocket },
  { name: "FiPower", icon: FiPower },
  { name: "FiPrinter", icon: FiPrinter },
  { name: "FiRefreshCw", icon: FiRefreshCw },
  { name: "FiRepeat", icon: FiRepeat },
  { name: "FiSave", icon: FiSave },
  { name: "FiScissors", icon: FiScissors },
  { name: "FiSend", icon: FiSend },
  { name: "FiServer", icon: FiServer },
  { name: "FiShare", icon: FiShare },
  { name: "FiShield", icon: FiShield },
  { name: "FiShoppingBag", icon: FiShoppingBag },
  { name: "FiSidebar", icon: FiSidebar },
  { name: "FiSmile", icon: FiSmile },
  { name: "FiSpeaker", icon: FiSpeaker },
  { name: "FiSquare", icon: FiSquare },
  { name: "FiSun", icon: FiSun },
  { name: "FiTablet", icon: FiTablet },
  { name: "FiTag", icon: FiTag },
  { name: "FiTarget", icon: FiTarget },
  { name: "FiTerminal", icon: FiTerminal },
  { name: "FiThumbsUp", icon: FiThumbsUp },
  { name: "FiTool", icon: FiTool },
  { name: "FiTrash", icon: FiTrash },
  { name: "FiTrendingUp", icon: FiTrendingUp },
  { name: "FiTruck", icon: FiTruck },
  { name: "FiTv", icon: FiTv },
  { name: "FiUpload", icon: FiUpload },
  { name: "FiVideo", icon: FiVideo },
  { name: "FiWifi", icon: FiWifi },
  { name: "FiWind", icon: FiWind },
  { name: "FiZap", icon: FiZap },
  { name: "FiZoomIn", icon: FiZoomIn },
  { name: "FiZoomOut", icon: FiZoomOut },
];